#
# PROGRAM:    assign2
# PROGRAMMER: Alex Boyle
#             z1759628
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
assignment2.exe: assignment2.cc
	g++ $(CCFLAGS) assignment2.cc -o assignment2.exe

clean:
	rm assignment2.exe
