#
# PROGRAM:    assign2
# PROGRAMMER: Alex Boyle
#             z1759628
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
assignment9.exe: assignment9.cc
	g++ $(CCFLAGS) assignment9.cc -o assignment9.exe

clean:
	rm assignment9.exe
