#
# PROGRAM:    assign6
# PROGRAMMER: Alex Boyle
#             z1759628
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
assignment6.exe: assignment6main.cc
	g++ -Wall -g -std=c++11 assignment5.cc assignment6.cc assignment6main.cc -o assignment6.exe

clean:
	rm assignment6.exe
