#
# PROGRAM:    assign2
# PROGRAMMER: Alex Boyle
#             z1759628
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
assignment8.exe: assignment8.cc
	g++ $(CCFLAGS) assignment8.cc -o assignment8.exe

clean:
	rm assignment8.exe
