#
# PROGRAM:    assign5
# PROGRAMMER: Alex Boyle
#             z1759628
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
assignment5.exe: assignment5.cc
	g++ $(CCFLAGS) assignment5.cc -o assignment5.exe

clean:
	rm assignment5.exe
