#
# PROGRAM:    assign2
# PROGRAMMER: Alex Boyle
#             z1759628
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
assignment3.exe: assignment4.cc
	g++ $(CCFLAGS) assignment4.cc -o assignment4.exe

clean:
	rm assignment4.exe
