#
# PROGRAM:    assign2
# PROGRAMMER: Alex Boyle
#             z1759628
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
assignment1.exe: assignment1.cc
	g++ $(CCFLAGS) assignment1.cc -o assignment1.exe

clean:
	rm assignment1.exe
