#
# PROGRAM:    assign5
# PROGRAMMER: Alex Boyle
#             z1759628
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
assignment7.exe: assignment7.cc
	g++ $(CCFLAGS) assignment7.cc -o assignment7.exe

clean:
	rm assignment7.exe
