#
# PROGRAM:    assign2
# PROGRAMMER: Alex Boyle
#             z1759628
#

# Compiler variables
CCFLAGS = -Wall

# Rule to link object code files to create executable file
assignment3.exe: assignment3.cc
	g++ $(CCFLAGS) assignment3.cc -o assignment3.exe

clean:
	rm assignment3.exe
